#!/usr/bin/env python3
"""
v1.3.1: GitHub / GitLab Pull-Request Integration

Builds the PR body, file list, and review comments for a generated feature.
The actual PR creation is delegated to the user's gh / glab CLI — this
module produces the inputs and a ready-to-run command.

Public API:
    pr = PRIntegration(provider='github', repo='org/repo')
    bundle = pr.build(
        feature='Rate limiter',
        files=[{'path': 'rate_limiter.py', 'kind': 'feature', 'loc': 180}, ...],
        review_findings=[{'severity': 'warn', 'message': 'consider Redis backend'}],
        branch='feature/rate-limiter',
    )
    # bundle = {
    #   'title': '...',
    #   'body': '...markdown...',
    #   'commands': ['git checkout -b ...', 'gh pr create ...'],
    # }
"""

from __future__ import annotations

import textwrap
from dataclasses import dataclass
from typing import Dict, List, Optional


@dataclass
class PRFile:
    path: str
    kind: str  # 'feature' | 'test' | 'migration' | 'doc' | 'config'
    loc: int = 0


class PRIntegration:
    """Build PR title / body / commands for generated code."""

    def __init__(self, provider: str = 'github', repo: str = '', base_branch: str = 'main'):
        self.provider = provider.lower()
        self.repo = repo
        self.base_branch = base_branch

    def build(self,
              feature: str,
              files: List[Dict],
              review_findings: Optional[List[Dict]] = None,
              branch: str = '',
              draft: bool = True) -> Dict:
        review_findings = review_findings or []
        branch = branch or self._suggest_branch(feature)

        title = self._title(feature)
        body = self._body(feature, files, review_findings)
        commands = self._commands(branch, title, body, draft=draft)

        return {
            'title': title,
            'body': body,
            'branch': branch,
            'commands': commands,
            'provider': self.provider,
            'repo': self.repo,
        }

    # ---- internals ---------------------------------------------------------

    def _title(self, feature: str) -> str:
        slug = feature.lower().strip().rstrip('.')
        # PR title style: short imperative summary, < 70 chars
        if not slug.startswith(('add', 'introduce', 'wire', 'replace')):
            slug = f"add {slug}"
        return slug[:68].rstrip(' .')

    def _suggest_branch(self, feature: str) -> str:
        slug = feature.lower().replace(' ', '-')
        slug = ''.join(ch for ch in slug if ch.isalnum() or ch == '-').strip('-')
        return f'feature/{slug}' if slug else 'feature/generated'

    def _body(self,
              feature: str,
              files: List[Dict],
              findings: List[Dict]) -> str:
        files_table = "\n".join(
            f"| `{f.get('path', '?')}` | {f.get('kind', '?')} | {f.get('loc', 0)} |"
            for f in files
        )

        finding_lines = "\n".join(
            f"- **{x.get('severity', 'info').upper()}**: {x.get('message', '')}"
            for x in findings
        ) or "- _no automated findings_"

        return textwrap.dedent(f"""\
            ## Summary
            Adds **{feature}** generated by `one-shot-prompting`. The change includes
            implementation, tests, and supporting configuration. Generated review
            findings are listed below; address or acknowledge before merging.

            ## Files
            | Path | Kind | LOC |
            |------|------|-----|
            {files_table}

            ## Automated review findings
            {finding_lines}

            ## How to test
            1. `pip install -r requirements.txt` (or framework equivalent).
            2. Run the test suite: `pytest -q` or `npm test` etc.
            3. Smoke-test the new endpoint / handler against a local instance.

            ## Rollback
            Revert this commit; the legacy path remains untouched.

            ---
            _Generated by one-shot-prompting `pr_integration.py`. Edit freely before merging._
            """)

    def _commands(self, branch: str, title: str, body: str, draft: bool) -> List[str]:
        body_inline = body.replace('"', '\\"')
        if self.provider == 'gitlab':
            return [
                f'git checkout -b {branch}',
                'git add -A',
                f'git commit -m "{title}"',
                f'git push -u origin {branch}',
                f'glab mr create --title "{title}" --description "{body_inline}" '
                f'{"--draft" if draft else ""} --target-branch {self.base_branch}',
            ]
        # github default
        return [
            f'git checkout -b {branch}',
            'git add -A',
            f'git commit -m "{title}"',
            f'git push -u origin {branch}',
            f'gh pr create --title "{title}" --body "{body_inline}" '
            f'{"--draft" if draft else ""} --base {self.base_branch}',
        ]


def main():
    pr = PRIntegration(provider='github', repo='example/example')
    bundle = pr.build(
        feature='Rate limiter for message.received events',
        files=[
            {'path': 'rate_limiter.py', 'kind': 'feature', 'loc': 180},
            {'path': 'tests/test_rate_limiter.py', 'kind': 'test', 'loc': 220},
            {'path': 'README.md', 'kind': 'doc', 'loc': 140},
        ],
        review_findings=[
            {'severity': 'warn', 'message': 'in-memory backend will not survive process restarts; consider Redis.'},
        ],
    )
    print(bundle['title'])
    print()
    print(bundle['body'])
    print()
    print('\n'.join(bundle['commands']))


if __name__ == '__main__':
    main()
