#!/usr/bin/env python3
"""
ADR Writer — v1.0.0  (Architecture Decision Record emission)

The architect agent produces spec.json — the WHAT. ADRs capture the WHY:
the alternatives considered, the trade-offs accepted, the constraints
that drove the choice. Spec.json answers "what did we build?"; the ADR
answers "why did we build it that way?"

Pattern: standard MADR-flavoured ADR (https://adr.github.io/madr/).
Sequential numbering under docs/adr/. One ADR per significant architectural
decision (NOT one per entity — one per design choice).

Inspired by Addy Osmani's documentation-and-adrs skill.

CLI (called by the architect agent OR run manually):
    adr_writer.py emit \
        --project <dir> \
        --title "Use SQLAlchemy 2.0 mapped_column over legacy Column" \
        --status "accepted" \
        --context "<paragraph: what's the problem?>" \
        --decision "<paragraph: what did we choose?>" \
        --consequences "<paragraph: what does this lock us into?>" \
        --alternatives "<bullet list: what else did we consider?>"

    adr_writer.py list --project <dir>

Outputs:
    docs/adr/{N}-{kebab-title}.md   — the new ADR (auto-numbered)
    docs/adr/README.md              — auto-regenerated index

Exit codes:
    0   ok
    1   bad args / project missing
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Optional

from lib.base_script import bootstrap_runtime, setup_logging
bootstrap_runtime()
logger = setup_logging(__name__)


ADR_DIR = Path("docs/adr")


def _kebab(s: str) -> str:
    s = re.sub(r"[^A-Za-z0-9]+", "-", s.strip().lower())
    return s.strip("-")[:60]


def _next_number(adr_dir: Path) -> int:
    if not adr_dir.exists():
        return 1
    nums = []
    for p in adr_dir.glob("*.md"):
        m = re.match(r"^(\d+)-", p.name)
        if m:
            nums.append(int(m.group(1)))
    return (max(nums) + 1) if nums else 1


def _today() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


def emit(project: Path, *, title: str, status: str = "accepted",
         context: str = "", decision: str = "",
         consequences: str = "", alternatives: str = "") -> Path:
    adr_dir = project / ADR_DIR
    adr_dir.mkdir(parents=True, exist_ok=True)
    number = _next_number(adr_dir)
    slug = _kebab(title) or f"decision-{number}"
    path = adr_dir / f"{number:04d}-{slug}.md"

    body = f"""---
adr_number: {number}
status: {status}
date: {_today()}
deciders: architect-agent
---

# {number}. {title}

## Status

**{status.capitalize()}** — {_today()}

## Context

{context.strip() or "(architect agent did not provide context — fill in)"}

## Decision

{decision.strip() or "(architect agent did not provide decision text — fill in)"}

## Consequences

{consequences.strip() or "(no consequences documented — fill in trade-offs accepted)"}

## Alternatives considered

{alternatives.strip() or "(no alternatives documented — fill in what else was on the table)"}

## References

- Generated alongside spec.json by /one-shot
- See [docs/adr/README.md](README.md) for the full index
"""
    path.write_text(body, encoding="utf-8")
    _rewrite_index(adr_dir)
    return path


def _rewrite_index(adr_dir: Path) -> None:
    entries: List[tuple] = []
    for p in sorted(adr_dir.glob("[0-9]*.md")):
        text = p.read_text(encoding="utf-8", errors="replace")
        # Extract title from the first h1
        m = re.search(r"^#\s+\d+\.\s+(.+)$", text, re.M)
        title = m.group(1).strip() if m else p.stem
        # Extract status from frontmatter
        sm = re.search(r"^status:\s*(\S+)\s*$", text, re.M)
        status = sm.group(1) if sm else "?"
        entries.append((p.name, title, status))

    lines = [
        "# Architecture Decision Records",
        "",
        "Sequential record of significant architectural decisions. "
        "Each ADR captures the WHY behind a design choice — context, "
        "alternatives considered, trade-offs accepted.",
        "",
        "Auto-generated by [adr_writer.py](../../skills/one-shot-generator/scripts/adr_writer.py). "
        "Do not hand-edit this index; edit individual ADRs and rerun "
        "`adr_writer.py list --project .`.",
        "",
        "| # | Title | Status |",
        "|---|---|---|",
    ]
    for filename, title, status in entries:
        lines.append(f"| [{filename}]({filename}) | {title} | **{status}** |")
    lines.append("")
    (adr_dir / "README.md").write_text("\n".join(lines), encoding="utf-8")


def list_adrs(project: Path) -> List[dict]:
    adr_dir = project / ADR_DIR
    if not adr_dir.exists():
        return []
    out: List[dict] = []
    for p in sorted(adr_dir.glob("[0-9]*.md")):
        text = p.read_text(encoding="utf-8", errors="replace")
        m_title = re.search(r"^#\s+(\d+)\.\s+(.+)$", text, re.M)
        m_status = re.search(r"^status:\s*(\S+)\s*$", text, re.M)
        out.append({
            "number": int(m_title.group(1)) if m_title else 0,
            "title": m_title.group(2).strip() if m_title else p.stem,
            "status": m_status.group(1) if m_status else "?",
            "path": str(p.relative_to(project)),
        })
    return out


# ─── CLI ────────────────────────────────────────────────────────────────────

def main(argv: Optional[List[str]] = None) -> int:
    p = argparse.ArgumentParser(description="Emit or list Architecture Decision Records.")
    sub = p.add_subparsers(dest="cmd", required=True)

    p_emit = sub.add_parser("emit", help="Create a new numbered ADR.")
    p_emit.add_argument("--project", required=True, type=Path)
    p_emit.add_argument("--title", required=True)
    p_emit.add_argument("--status", default="accepted",
                        choices=["proposed", "accepted", "deprecated", "superseded"])
    p_emit.add_argument("--context", default="")
    p_emit.add_argument("--decision", default="")
    p_emit.add_argument("--consequences", default="")
    p_emit.add_argument("--alternatives", default="")

    p_list = sub.add_parser("list", help="List all ADRs in the project.")
    p_list.add_argument("--project", required=True, type=Path)

    args = p.parse_args(argv if argv is not None else sys.argv[1:])

    if not args.project.exists():
        print(f"project not found: {args.project}", file=sys.stderr)
        return 1

    if args.cmd == "emit":
        path = emit(args.project, title=args.title, status=args.status,
                    context=args.context, decision=args.decision,
                    consequences=args.consequences,
                    alternatives=args.alternatives)
        print(json.dumps({"adr_path": str(path.relative_to(args.project)),
                          "number": int(path.name.split("-", 1)[0])}, indent=2))
        return 0

    if args.cmd == "list":
        print(json.dumps(list_adrs(args.project), indent=2))
        return 0

    return 1


if __name__ == "__main__":
    sys.exit(main())
