#!/usr/bin/env python3
"""
MCP GitHub Approval Server — optional integration for zone gates.

Implements Model Context Protocol (MCP) for GitHub approval workflows:
- POST: Send approval request to a GitHub PR
- GET: Poll for approval decision from PR comments
- RESPOND: Post decision back to the pipeline

This is a **skeleton implementation** showing the pattern. Users can:
1. Run this MCP server alongside Claude Code
2. Wire the zone gates to POST approval requests to GitHub
3. Approval comments on the PR are picked up and routed back to the pipeline

Usage:

    # Start MCP server (listens on stdio)
    python mcp_github_approval.py --mode server

    # Test: POST approval request
    curl -X POST http://localhost:8000/api/approval \
        --data '{"pr_number": 123, "repo": "owner/repo", "message": "..."}'

    # Test: GET approval decision
    curl http://localhost:8000/api/approval/decision \
        --data '{"pr_number": 123, "repo": "owner/repo"}'

Environment variables (required for real use):
    GITHUB_TOKEN — GitHub personal access token (for API calls)
    GITHUB_REPO — "owner/repo" format
"""

import json
import os
import sys
from dataclasses import dataclass
from datetime import datetime
from typing import Optional


@dataclass
class ApprovalRequest:
    """Structured approval request for GitHub PR."""

    pr_number: int
    repo: str  # "owner/repo"
    spec_summary: str
    cost_estimate: Optional[str] = None
    entities: Optional[list[str]] = None
    created_at: str = None

    def __post_init__(self):
        if not self.created_at:
            self.created_at = datetime.now().isoformat()

    def to_github_comment(self) -> str:
        """Format as a GitHub PR comment for approvers."""
        comment = f"""
## Zone Approval Gate — PLAN → BUILD

The architect has designed a spec. Please review and approve before code generation:

### Spec Summary
{self.spec_summary}

"""
        if self.cost_estimate:
            comment += f"### Cost Estimate\n{self.cost_estimate}\n\n"

        if self.entities:
            comment += f"### Entities\n" + "\n".join(f"- {e}" for e in self.entities) + "\n\n"

        comment += """### Decision

Please reply with one of:
- `@bot approve` — Proceed to BUILD zone (code generation)
- `@bot deny` — Abort this run, no code generation
- `@bot revise` — Return to architect, revise spec

*This comment was auto-generated by one-shot-prompting/MCP GitHub Approval*
"""
        return comment


@dataclass
class ApprovalDecision:
    """Decision returned from GitHub PR review."""

    status: str  # "approved" | "denied" | "pending"
    decided_by: Optional[str] = None  # GitHub username
    comment: Optional[str] = None
    decided_at: Optional[str] = None

    def __post_init__(self):
        if not self.decided_at and self.status != "pending":
            self.decided_at = datetime.now().isoformat()


def parse_approval_comment(comment_text: str) -> Optional[ApprovalDecision]:
    """
    Parse a GitHub PR comment for approval decision.
    Looks for: "@bot approve", "@bot deny", "@bot revise"
    """
    lower = comment_text.lower()

    if "@bot approve" in lower:
        return ApprovalDecision(status="approved", comment=comment_text)
    elif "@bot deny" in lower:
        return ApprovalDecision(status="denied", comment=comment_text)
    elif "@bot revise" in lower:
        return ApprovalDecision(status="pending", comment=comment_text)

    return None


def simulate_approval_flow(request: ApprovalRequest) -> ApprovalDecision:
    """
    Simulate approval flow (for testing without actual GitHub).
    In real use, this would:
    1. POST ApprovalRequest.to_github_comment() as a PR comment
    2. Poll PR comments for approval decision
    3. Return ApprovalDecision
    """
    print(f"\n[MCP] Simulating approval flow for PR #{request.pr_number}")
    print(f"[MCP] Comment:\n{request.to_github_comment()}")
    print(f"[MCP] (In real use, this would be posted to GitHub; awaiting approval comment)")

    # For simulation, default to approved
    return ApprovalDecision(
        status="approved",
        decided_by="simulated-user",
        comment="(simulated approval)",
    )


def get_approval_decision(
    pr_number: int,
    repo: str,
    timeout_seconds: int = 3600,
) -> ApprovalDecision:
    """
    Poll GitHub PR for approval decision in comments.
    Returns ApprovalDecision when found, or status=pending after timeout.
    """
    github_token = os.getenv("GITHUB_TOKEN")
    if not github_token:
        return ApprovalDecision(
            status="pending",
            comment="GITHUB_TOKEN not set; cannot poll GitHub. (Set env var to enable real approval)",
        )

    # Real implementation would use github API:
    # GET /repos/{owner}/{repo}/pulls/{pr}/comments
    # and parse approval commands

    # For now, return pending (skeleton)
    return ApprovalDecision(status="pending", comment="(skeleton: real GitHub polling not yet implemented)")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: mcp_github_approval.py [simulate|server|test]")
        sys.exit(1)

    mode = sys.argv[1]

    if mode == "simulate":
        # Test: simulate an approval request → decision flow
        request = ApprovalRequest(
            pr_number=123,
            repo="owner/repo",
            spec_summary="Add shopping cart with line items and discounts",
            cost_estimate="$0.45",
            entities=["ShoppingCart", "LineItem", "Discount"],
        )
        decision = simulate_approval_flow(request)
        print(f"\nDecision: {decision.status}")

    elif mode == "server":
        print("MCP GitHub Approval Server — skeleton mode (not yet implemented)")
        print("Real implementation would start an MCP server on stdio.")

    elif mode == "test":
        # Test approval comment parsing
        test_comments = [
            "@bot approve — looks good",
            "@bot deny — spec needs revision",
            "@bot revise — please adjust cost estimate",
            "This looks okay to me",  # No approval command
        ]
        for comment in test_comments:
            decision = parse_approval_comment(comment)
            print(f"Comment: {comment:40} → {decision.status if decision else 'none'}")

    else:
        print(f"Unknown mode: {mode}")
        sys.exit(1)
